### ISSUE TITLE
studio: Dega is not routing to Kavach in a few cases when the user is not logged in

### ISSUE THREAD

**Issue by deshetti** [factly/dega#146]
If the user is logged out after some time and tries to load Dega, it just opens a blank page and is not routed to Kavach.

<img width="1136" alt="Screen Shot 2021-05-19 at 9 58 11 AM" src="https://user-images.githubusercontent.com/10763210/118836464-794c3580-b889-11eb-87cf-ab43a3ba08d2.png">

After we get the blank screen, if we reload the page again it then routes to Kavach as expected for logging in.

**Comment by vsumit89** [comment]
duplicate of #173
