### ISSUE TITLE
studio: Provide a field to convert the EditorJS blocks into HTML.

### ISSUE THREAD

**Issue by deshetti** [factly/dega#265]
This would be required for us to expose REST APIs/ RSS feeds to third party content aggregators

Here is the discussion for this requirement: https://github.com/codex-team/editor.js/issues/676

Here is a utility discussed in the above issue that seems to have support for most of the default blocks: https://github.com/pavittarx/editorjs-html

And this one for React: https://github.com/BomdiZane/EditorJS-React-Renderer

**Comment by deshetti** [comment]
@hetjagani Do we still need this issue? I believe you have already implemented this on the server, right? Why would we need to do this on the studio side of things?

**Comment by hetjagani** [comment]
Ya this is implemented. We do not need anything on studio side.

**Comment by deshetti** [comment]
Closing the issue as it is already implemented
