### ISSUE TITLE
Don't fail `dega-server` and `dega-api` over Meili and Redis failures

### ISSUE THREAD

**Issue by deshetti** [factly/dega#324]
Currently, `dega-api` and `dega-server` would fail during startup if caching is enabled and Redis connectivity fails and if Meili's connectivity fails. Meili and Redis are supporting services and the core functionality should still be working regardless. Here is what I propose for us to do:

If Redis is down:
- [x] Throw an error and continue with startup
- [x] When querying, if Redis throws a connectivity error skip and get data from PG instead

If Meili is down:
- [x] Throw an error and continue with startup
- [x] Throw error when search requests are made

**Comment by hetjagani** [comment]
When meili is down it returns **empty** result on search with filters/query. Should this be fine or should we throw **error** instead?

**Comment by hetjagani** [comment]
Making this change on  feat/optional_meili_config branch.
