### ISSUE TITLE
Setup shortcuts on the Editor

### ISSUE THREAD

**Issue by deshetti** [factly/dega#335]
Setup the following shortcuts based on the Notion: https://usethekeyboard.com/notion/#ContentCreation&Editing

Mac and Windows shortcuts would differ. Change the toggle button displayed on top of the page from the above URL to see what the shortcut keys for Windows would be.

Here is some info on how to setup shortcuts on EditorJS:
- https://editorjs.io/inline-tool-advanced-methods
- Use the following codec: https://github.com/codex-team/codex.shortcuts

**Comment by Bhumi101097** [comment]
Header  : shortcut: 'CMD+OPTION+1',
List  : shortcut: 'CMD+OPTION+6,
Paragraph  : shortcut: 'CMD+OPTION+0’,
Quote  : shortcut: 'CMD+OPTION+O’,
RawTool  : shortcut: 'CMD+OPTION+R,
Table  : shortcut: 'CMD+OPTION+T,
CodeTool  : shortcut: 'CMD+OPTION+8’,
InlineCode  : shortcut: 'CMD+E’,
Marker  : shortcut: 'CMD+OPTION+H’,
Embed  : shortcut: 'CMD+OPTION+E’,
