### ISSUE TITLE
Docker / error messages in console / exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by johndpope** [factly/dega#408]
dega_hukz-migrate_1 exited with code 0
iframely_1        | data:    cluster.js:33 - Using cache engine: node-cache
dega-templates_1  | 2021/08/10 00:38:04 Error while building:
dega-templates_1  |  # github.com/mattn/go-sqlite3
dega-templates_1  | exec: "gcc": executable file not found in $PATH
dega-templates_1  |
companion_1       | companion: 2021-08-10T00:38:08.595Z [warn] startup.secret auto-generating server secret because none was specified
companion_1       | companion: 2021-08-10T00:38:08.597Z [warn] startup.secret auto-generating server secret because none was specified
companion_1       | companion: 2021-08-10T00:38:08.608Z [info] jobs.cleanup.start starting clean up job
companion_1       | Welcome to Companion! v2.5.1
companion_1       | Listening on http://0.0.0.0:3020
dega-api_1        | 2021/08/10 00:38:08 Error while building:
dega-api_1        |  # github.com/mattn/go-sqlite3
dega-api_1        | exec: "gcc": executable file not found in $PAT

**Comment by shreeharsha-factly** [comment]
@johndpope Docker issue was fixed and updated docker files.
