### ISSUE TITLE
Docker - intial login

### ISSUE THREAD

**Issue by johndpope** [factly/dega#409]
I renamed all the config.env.example -> config.env and ran docker-compose up

When I get to the login screen - I attempt to use 
DEFAULT_USER_EMAIL=admin@dega.in
DEFAULT_USER_PASSWORD=password

It doesn't login - I see these errors in console.

Creating new user doesn't work. Can't get in.

y":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","remote":"172.18.0.1:57456","scheme":"http"},"http_response":{"status":200,"text_status":"OK","took":2222173},"level":"info","msg":"completed handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | [cors] 2021/08/10 01:07:43 Handler: Actual request
oathkeeper_1      | [cors] 2021/08/10 01:07:43   Actual request no headers added: missing origin
oathkeeper_1      | {"http_request":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/favicon.ico","query":null,"remote":"172.18.0.1:57456","scheme":"http"},"level":"info","msg":"started handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"audience":"application","error":{"debug":"","message":"Requested url does not match any rules","reason":"","status":"Not Found","status_code":404},"granted":false,"http_host":"127.0.0.1:4455","http_method":"GET","http_url":"http://127.0.0.1:4455/.factly/kavach/web/favicon.ico","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","level":"warning","msg":"Access request denied","service_name":"ORY Oathkeeper","service_version":"v0.38.14-beta.1","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"code":404,"debug":"","details":{},"error":"Requested url does not match any rules","level":"error","msg":"An error occurred while handling a request","reason":"","request-id":"","status":404,"time":"2021-08-10T01:07:43Z","writer":"JSON"}
oathkeeper_1      | {"http_request":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/favicon.ico","query":null,"remote":"172.18.0.1:57456","scheme":"http"},"http_response":{"status":404,"text_status":"Not Found","took":1199864},"level":"info","msg":"completed handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | [cors] 2021/08/10 01:07:43 Handler: Actual request
oathkeeper_1      | [cors] 2021/08/10 01:07:43   Actual request no headers added: missing origin
oathkeeper_1      | {"http_request":{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","if-modified-since":"Sun, 07 Mar 2021 18:16:38 GMT","if-none-match":"W/\"1ec-1780de7cb70\"","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/manifest.json","query":null,"remote":"172.18.0.1:57588","scheme":"http"},"level":"info","msg":"started handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"audience":"application","granted":true,"http_host":"127.0.0.1:4455","http_method":"GET","http_url":"http://kavach-web:3000/.factly/kavach/web/manifest.json","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","level":"warning","msg":"Access request granted","service_name":"ORY Oathkeeper","service_version":"v0.38.14-beta.1","subject":"guest","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"http_request":{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","if-modified-since":"Sun, 07 Mar 2021 18:16:38 GMT","if-none-match":"W/\"1ec-1780de7cb70\"","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/manifest.json","query":null,"remote":"172.18.0.1:57588","scheme":"http"},"http_response":{"status":304,"text_status":"Not Modified","took":2544453},"level":"info","msg":"completed handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"http_request":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/logo192.png","query":null,"remote":"172.18.0.1:57456","scheme":"http"},"level":"info","msg":"started handling request","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | [cors] 2021/08/10 01:07:43 Handler: Actual request
oathkeeper_1      | [cors] 2021/08/10 01:07:43   Actual request no headers added: missing origin
oathkeeper_1      | {"audience":"application","error":{"debug":"","message":"Requested url does not match any rules","reason":"","status":"Not Found","status_code":404},"granted":false,"http_host":"127.0.0.1:4455","http_method":"GET","http_url":"http://127.0.0.1:4455/.factly/kavach/web/logo192.png","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","level":"warning","msg":"Access request denied","service_name":"ORY Oathkeeper","service_version":"v0.38.14-beta.1","time":"2021-08-10T01:07:43Z"}
oathkeeper_1      | {"code":404,"debug":"","details":{},"error":"Requested url does not match any rules","level":"error","msg":"An error occurred while handling a request","reason":"","request-id":"","status":404,"time":"2021-08-10T01:07:43Z","writer":"JSON"}
oathkeeper_1      | {"http_request":{"headers":{"accept":"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","referer":"http://127.0.0.1:4455/.factly/kavach/web/auth/login?flow=cc2485e1-c392-4bf0-87a8-8e8ed3a5ae20","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"},"host":"127.0.0.1:4455","method":"GET","path":"/.factly/kavach/web/logo192.png","query":null,"remote":"172.18.0.1:57456","scheme":"http"},"http_response":{"status":404,"text_status":"Not Found","took":338748},"level":"info","msg":"completed handling request","time":"2021-08-10T01:07:43Z"}

**Comment by shreeharsha-factly** [comment]
@johndpope User might be not be created due to weak password. 
Password must contain
- At least 8 characters
- A mixture of both numbers, uppercase and lowercase letters
- Inclusion of at least one special character

Update credentials as below and restart  dega-migrate container by `docker-compose restart dega-migrate`
```
DEFAULT_USER_EMAIL=admin@dega.in
DEFAULT_USER_PASSWORD=2ssad32sadADSd@!@4
```

**Comment by johndpope** [comment]
thank you.
