### ISSUE TITLE
License clarification - 

### ISSUE THREAD

**Issue by johndpope** [factly/dega#411]
this other repo has gpl license -
https://github.com/daptin/daptin

This is not suitable for commercial applications.
https://en.wikipedia.org/wiki/Viral_license

**Comment by deshetti** [comment]
@johndpope not sure what you are referring to. we will not be using https://github.com/daptin/daptin in dega regardless. daptin seems like a headless CMS which is partly what dega is as well.

Dega and most of the other projects at Factly are MIT licensed.

**Comment by johndpope** [comment]
It’s missing in the license.me in repo.

**Comment by johndpope** [comment]
I see it’s fixed. This is great. 
I think this repo is so good / belongs on product hunt once you guys are happy with it.

**Comment by deshetti** [comment]
> I see it’s fixed. This is great.

We recently merged the different microservices in dega into one repo and forgot to update the license. Fixed it yesterday.

> I think this repo is so good / belongs on product hunt once you guys are happy with it.

Thanks for checking it out. Plan is to get to Product Hunt once we have the beta ready
