### ISSUE TITLE
Fyi - on mac - Docker desktop seems to take port 5000 by default.

### ISSUE THREAD

**Issue by johndpope** [factly/dega#415]
Creating dega_kavach-server_1  ... error

ERROR: for dega_kavach-server_1  Cannot start service kavach-server: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use

I can get around this by modifying the port - which does remove error - but perhaps we could change this port to 5100 ?

**Comment by shreeharsha-factly** [comment]
@johndpope Some other service might be using 5000 port. I don't think Docker desktop takes 5000 port by 
default.
