### ISSUE TITLE
Unable to fetch Claims in fact Check Creation Page

### ISSUE THREAD

**Issue by atomsalt** [factly/dega#499]
Unable to fetch Claims in fact Check Creation Page
Tried to search for existing Claim, but getting Connection Failed 503 ERROR

Will Smith slapping Chris Rock is an example of how Hinduism makes one violent – Rana Ayyub

**Comment by deshetti** [comment]
@sshankaramanchi are you referring to not all fact checks to be available in Google Fact Check APIs? Or is this related to Dega?
