### ISSUE TITLE
Dega Server is restarting on Fatal Errors which are not really Fatal

### ISSUE THREAD

**Issue by deshetti** [factly/dega#505]
I am working on setting integration with Meili on Dega Server and currently, the server is restarting every time I perform a reindex on a space with the following error:

```
2022/05/02 21:14:13 /home/runner/work/dega/dega/server/service/reindex/space.go:36
[0.672ms] [rows:1] [request_id:-] SELECT * FROM "spaces" WHERE "spaces"."deleted_at" IS NULL AND "spaces"."id" = 8 ORDER BY "spaces"."id" LIMIT 1
2022/05/02 21:14:13 unaccepted status code found: 400 expected: [200], message from api: 'error parsing filter;  --> 1:1
  |
1 | space_id=8
  | ^------^
  |
  = attribute `space_id` not found, available attributes are: name, tag_line, site_title, description, kind, review_tag_line, slug, claim, title, site_address, fact, excerpt, object_id, review, subtitle', request: {"filters":"space_id=8","q":""} (path "POST /indexes/dega/search" with method "Search.Search")
 ```
The service is restarting everytime it hits an error which is termed as `fatal` in the code. https://github.com/factly/dega/blob/develop/server/service/reindex/space.go#L55

Searching through the code for `log.Fatal` gives me the following results. Go through all of these and change to `log.Error(err)` for the ones that are not supposed to be fatal.

**Comment by surajmn1** [comment]
@shreeharsha-factly this has been address already . closing the issue .
