### ISSUE TITLE
Removing Ok button and moving cancel button to the top in Claims Block inside a factcheck create page 

### ISSUE THREAD

**Issue by fyrepenguin** [factly/dega#540]
In Factcheck editPage or createPage, the modal we're having for editing claims has an update button on top and an ok and a cancel button at the bottom of the modal, moving the cancel button to the top and removing the OK button would make it less confusing.

**Comment by surajmn1** [comment]
https://github.com/factly/dega/pull/541 

seems to be resolved in this pr for another issue #528
