### ISSUE TITLE
Fact Checks - Filter by Category and Tag is not working - Fact check has Multiple Categories and if we have matching Category in fact-check, it should display the Fact check

### ISSUE THREAD

**Issue by atomsalt** [factly/dega#562]
Fact Checks - Filter by Category and Tag is not working - Fact check has Multiple Categories and if we have matching Category in fact-check, it should display the Fact check
Two issues here:
1. When we select one Category, it is not displaying the Result even though Fact check has that Category selected.
2. When we select all Categories of the Fact check, also it is not displaying the Result.
3. When we select one Tag, it is not displaying the Result even though Fact check has that Tag selected.

**Comment by deshetti** [comment]
Closing the issue as we are not able to replicate it. Confirmed with @sshankaramanchi that it is working as expected.
