### ISSUE TITLE
Change the UX to create new posts out of templates

### ISSUE THREAD

**Issue by deshetti** [factly/dega#584]
Currently, just clicking on the template is directly creating a post. We need to show a prompt to the user to confirm a new post should be created based on the template without silently creating the post.

**Comment by deshetti** [comment]
@shreeharsha-factly @surajmn1 Let's have a third button with a tooltip as described in [this issue](https://github.com/factly/dega/issues/564#issuecomment-1135077566) instead of creating a post by just clicking the template. I am still not very convinced if that is a good practice.

Add the following text to the tooltips:
- Create New
- Edit Template

Delete is self-explanatory and would not need a tooltip.

**Comment by surajmn1** [comment]
@shreeharsha-factly we have discussed with team and decided that this change was not necessary .
