### ISSUE TITLE
Dega Studio - When we add new space and click Submit, Space is added but getting below ERROR on page

### ISSUE THREAD

**Issue by atomsalt** [factly/dega#718]
Dega Studio - When we add new space and click Submit, Space is added but getting below ERROR on page

TypeError: services is undefined
./src/components/GlobalNav/Sidebar.js/Sidebar/<
src/components/GlobalNav/Sidebar.js:161

  158 | >
  159 |   {sidebarMenu.map((menu, index) => {
  160 |     const { Icon } = menu;
> 161 |     return menu.title === 'CORE' && !showCoreMenu
      | ^  162 |       ? null
  163 |       : !menu.isService
  164 |       ? !menu.isAdmin

**Comment by shreeharsha-factly** [comment]
Service is removed.
