### ISSUE TITLE
In graphql client schema is not loading

### ISSUE THREAD

**Issue by shreeharsha-factly** [factly/dega#757]
<img width="339" alt="Screenshot 2022-09-07 at 9 36 13 PM" src="https://user-images.githubusercontent.com/55734346/188926550-cd393d05-27f4-410e-bd2a-b71fcd240515.png">

**Comment by surajmn1** [comment]
this issue is caused due to incorrect input in graphql request headers , to resolve this 
1) correct the request headers input 
2) run the query 
3) refresh the page
