### ISSUE TITLE
Search Queries not working with SQLite

### ISSUE THREAD

**Issue by vsumit89** [factly/dega#779]
When meilisearch is disabled we use db(sqlite/postgres) for searching but when we use SQLite as the database, the search queries we have are throwing error. Reason for the error - SQLite doesn't support the keyword ILIKE. We are using ILIKE because it searches texts case insensitively.

**Comment by surajmn1** [comment]
https://github.com/factly/dega/commit/c6b839658356743ffe8b16efd2a53332600ec349  we have fixed this issue .
